### ISSUE TITLE
rmilter process died

### ISSUE THREAD

**Issue by anoter** [vstakhov/rmilter#71] opened 2016-01-19 11:33 UTC
Jan 19 14:16:13 host postfix/cleanup[2829]: warning: milter inet:localhost:11332: can't read SMFIC_HEADER reply packet header: Success
...
Jan 19 14:16:22 host postfix/smtpd[2820]: warning: connect to Milter service inet:localhost:11332: Connection refused

( Gentoo / postfix-3.0.2 / rmilter 1.7.0 )

**Comment by vstakhov** [comment] 2016-01-19 11:36
No information given. Is there anything related to rmilter and not postfix itself in the logs?

**Comment by anoter** [comment] 2016-01-19 12:19
Jan 19 14:16:13 host kernel: rmilter[2867]: segfault at 7fafac021024 ip 00007fafbc3288de sp 00007fafb8c659c8 error 4 in libc-2.21.so[7fafbc299000+193000]
Jan 19 14:25:47 host kernel: rmilter[20385]: segfault at 7fe124021034 ip 00007fe136ef08de sp 00007fe13382d9c8 error 4 in libc-2.21.so[7fe136e61000+193000]

**Comment by pfactum** [comment] 2016-01-19 14:14
Same crap for me. Here is stacktrace:

```
systemd-coredump[12254]: Process 12223 (rmilter) of user 978 dumped core.
                                                   
                                                   Stack trace of thread 12228:
                                                   #0  0x00007f2255e3c02e __memcpy_avx_unaligned (libc.so.6)
                                                   #1  0x000000000040b0d3 blake2b_update (rmilter)
                                                   #2  0x000000000041d70e check_message_id (rmilter)
                                                   #3  0x000000000041e87c mlfi_header (rmilter)
                                                   #4  0x0000000000424c7b mi_engine (rmilter)
                                                   #5  0x0000000000421cc6 mi_worker (rmilter)
                                                   #6  0x00007f22560bf4a4 start_thread (libpthread.so.0)
                                                   #7  0x00007f2255dfd13d __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 12229:
                                                   #0  0x00007f22560c5428 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x0000000000421ef1 mi_worker (rmilter)
                                                   #2  0x00007f22560bf4a4 start_thread (libpthread.so.0)
                                                   #3  0x00007f2255dfd13d __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 12225:
                                                   #0  0x00007f22560c8af7 do_sigwait (libpthread.so.0)
                                                   #1  0x00007f22560c8b6d sigwait (libpthread.so.0)
                                                   #2  0x00000000004234a2 mi_signal_thread (rmilter)
                                                   #3  0x00007f22560bf4a4 start_thread (libpthread.so.0)
                                                   #4  0x00007f2255dfd13d __clone (libc.so.6)

                                                   Stack trace of thread 12226:
                                                   #0  0x00007f2255df418d poll (libc.so.6)
                                                   #1  0x0000000000421715 mi_pool_controller (rmilter)
                                                   #2  0x00007f22560bf4a4 start_thread (libpthread.so.0)
                                                   #3  0x00007f2255dfd13d __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 12230:
                                                   #0  0x00007f22560c5428 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x0000000000421ef1 mi_worker (rmilter)
                                                   #2  0x00007f22560bf4a4 start_thread (libpthread.so.0)
                                                   #3  0x00007f2255dfd13d __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 12224:
                                                   #0  0x00007f22560c507f pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x000000000041aab9 reload_thread (rmilter)
                                                   #2  0x00007f22560bf4a4 start_thread (libpthread.so.0)
                                                   #3  0x00007f2255dfd13d __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 12227:
                                                   #0  0x00007f22560c5428 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x0000000000421ef1 mi_worker (rmilter)
                                                   #2  0x00007f22560bf4a4 start_thread (libpthread.so.0)
                                                   #3  0x00007f2255dfd13d __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 12223:
                                                   #0  0x00007f2255df418d poll (libc.so.6)
                                                   #1  0x0000000000420dd5 mi_listener (rmilter)
                                                   #2  0x0000000000420117 smfi_main (rmilter)
                                                   #3  0x00000000004095bb main (rmilter)
                                                   #4  0x00007f2255d34610 __libc_start_main (libc.so.6)
                                                   #5  0x0000000000409849 _start (rmilter)
```

**Comment by pfactum** [comment] 2016-01-19 14:19
Detailed gdb output:

```
#0  0x00007f2255e3c02e in __memcpy_avx_unaligned () from /usr/lib/libc.so.6
#1  0x000000000040b0d3 in blake2b_update (S=S@entry=0x7f22533c3a00, in=<optimized out>, 
    in@entry=0x7f22380009ac "<20160119141024.3XglMipSH%oleksandr@natalenko.name>", inlen=<optimized out>)
    at /home/pf/src/aur/rmilter/src/rmilter-1.7.0/compat/blake2b-ref.c:290
#2  0x000000000041d70e in check_message_id (priv=priv@entry=0x7f223c000940, 
    header=header@entry=0x7f22380009ac "<20160119141024.3XglMipSH%oleksandr@natalenko.name>")
    at /home/pf/src/aur/rmilter/src/rmilter-1.7.0/src/rmilter.c:255
#3  0x000000000041e87c in mlfi_header (ctx=0x187f320, headerf=0x7f22380009a0 "In-Reply-To", 
    headerv=0x7f22380009ac "<20160119141024.3XglMipSH%oleksandr@natalenko.name>")
    at /home/pf/src/aur/rmilter/src/rmilter-1.7.0/src/rmilter.c:897
#4  0x0000000000424c7b in mi_engine ()
#5  0x0000000000421cc6 in mi_worker ()
#6  0x00007f22560bf4a4 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007f2255dfd13d in clone () from /usr/lib/libc.so.6
```

**Comment by vstakhov** [comment] 2016-01-19 14:20
The problem is clear now, thank you!

**Comment by vstakhov** [comment] 2016-01-19 14:22
That should be fixed now

**Comment by pfactum** [comment] 2016-01-19 14:30
Confirm the fix to work, thanks.

**Closed** 2016-01-19 16:29 UTC
