### ISSUE TITLE
Add an Authentication-Results header

### ISSUE THREAD

**Issue by wildstray** [vstakhov/rmilter#28] opened 2015-04-30 13:24 UTC
An Authentication-Results header will be useful for debugging purposes and as a validation of a legitimate sender from a legitimate server.

Eg. (GMail Authentication-Results)

Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of foo@mydomain.it designates 2.10.10.10 as permitted sender) smtp.mail=foo@mydomain.it;
       dkim=pass header.i=@mydomain.it;
       dmarc=pass (p=NONE dis=NONE) header.from=mydomain.it
##

**Comment by vstakhov** [comment] 2015-04-30 15:09
To tell the truth, DKIM, DMARC and SPF checks are intended to be done on rspamd side. But rmilter can obviously add this information somehow.

**Comment by wildstray** [comment] 2015-05-01 14:07
Authentication-Results is documented by RFC5451 (but it might exists an updated RFC because I seen also dmarc Authentication-Results in GMail or header added by opendmarc).
About generation it rspamd side, I often implemented mail systems in this way: 
email from external source (legitimate MTA or bot or spammer) ---> dnsbl (postfix postscreen or, in the past, postfix smtpd_recipient_restrictions rules) ---> spf/dkim/dmarc (reject) ---> clamav (reject) ---> spamassassin (tag).
My logic is to reject messages ASAP and with the lightest possible controls and with a separation between source/sender/headers checking and message content checking. The messages that seems to be legitimate to dnsbl, local blacklists, dkim, spf, are verified thru clamav, thru spamassassin (bayes) and marked (or rejected in case of attached virus or significant spam scoring).
Rspamd is dramatically fast than SA, so there isn't the problem of using it "as a last resource", but might be interesting to supply rmilter of "full loaded" tools to mark/reject (eg. dmarc is missing) email autonomously, indipendently from dspam. Obviously spf/dkim/dmarc results can contribute, later, to the spam score.
PS: Please don't abandon this project, it's promising, it can replace "all-in-one" many milters, script and libraries.

**Comment by vstakhov** [comment] 2015-05-04 11:26
The reason why I don't like this project is simple: so far, rspamd can do almost all things supported in rmilter but *significantly* faster than rmilter.  The only missing thing is the milter protocol interface for rspamd. Hence, I'm looking forward to adopt rspamd to understand milter protocol directly than to add more hacks to rmilter.

**Comment by wangyu1314** [comment] 2016-05-04 05:54
Authentication-Results header is  useful , hope it come as  soon as probably .

**Comment by devurandom** [comment] 2017-02-04 01:14
It appears #65 is a duplicate of this.

@vstakhov Is rmilter still necessary for integration with Postfix?

**Comment by fatalbanana** [comment] 2017-02-04 09:39
I'm a little confused as to quite what #65 is really about.

Support for adding Authentication-Results header is [https://rspamd.com/doc/modules/rmilter_headers.html](available in rspamd) - rmilter is able to use this.

**Closed** 2017-02-04 10:10 UTC
