### ISSUE TITLE
can't read SMFIC_DATA reply packet header: Connection timed out

### ISSUE THREAD

**Issue by dehnli** [vstakhov/rmilter#56] opened 2015-11-21 19:06 UTC
After update to 1.6.6 there are such errors in /var/log/maillog:
Nov 21 21:30:31 mx postfix/smtpd[16619]: warning: milter inet:rspamd:9900: can't read SMFIC_DATA reply packet header: Connection timed out
Nov 21 21:50:41 mx postfix/cleanup[16920]: warning: milter inet:rspamd:9900: can't read SMFIC_BODYEOB reply packet header: Connection timed out

but:
telnet rspamd 9900
Trying rspamd...
Connected to rspamd.
Escape character is '^]'.

**Comment by achch** [comment] 2015-11-23 14:39
a similar problem. If you do service rmilter restart, the command hangs, only helps kill -s 9 pid
FreeBSD 10.0-RELEASE-p18

**Comment by vstakhov** [comment] 2015-11-23 17:13
This should be fixed by https://github.com/vstakhov/rmilter/commit/e84cfe09f2c3c27dcd1395d5c01bd900a1b1212e

**Comment by achch** [comment] 2015-11-23 17:59
I updated a few hours ago to version 1.6.6 (pkg upgrade) with the result that it stopped working.
I immediately updated the ports tree and make the rmilter 1.6.6 on the other an experimental server. The result is the same.
Also make version 1.6.5, it worked, but in a strange way. sometimes it started without any problems, but then at the restart could hang. after the forced "kill -s 9 pid" of normal start, but there were reports in the logs -> Connection timed out
Now I rolled to version 1.6.1. it is stable.
I can be of any help to clarify this issue?

**Comment by vstakhov** [comment] 2015-11-23 18:29
This problem is fixed in git. I'll include the corresponding patches in the port soon.

**Comment by kAworu** [comment] 2015-11-24 16:42
hi @achch ,

If you got a working port tree, could you try the patch ? Here is the process to build and install a patched rmilter 1.6.6:
```
% cd /usr/ports/mail/rmilter
% sudo make patch
% cd work/rmilter-1.6.6
% fetch --output=/dev/stdout https://gist.githubusercontent.com/kAworu/15278e6886f6f53672ab/raw/a36034345cbb0184b6b5ca416a91069c89e8dff9/rmilter.freebsd.unix.socket.hang.patch | sudo patch -p0
% cd /usr/ports/mail/rmilter
% sudo make
% sudo service rmilter stop
% sudo make deinstall reinstall clean
% sudo service rmilter start
```

**Comment by kAworu** [comment] 2015-11-24 16:43
Also see #48, as a workaround you can bind to a TCP port instead of using a UNIX socket and it should work.

**Comment by dehnli** [comment] 2015-11-24 18:37
hi @kAworu

1. Thanks for patch!
I tried it on FreeBSD 10.1-RELEASE-p24 GENERIC, but unfortunately have the same error:  
Nov 24 21:27:36 mx postfix/smtpd[14178]: warning: milter inet:rmilter:9900: can't read SMFIC_DATA reply packet header: Connection timed out

2. I bound rmilter to a TCP port, but it doesn't help 
/usr/local/etc/rc.d/rmilter stop
Stopping rmilter.
Waiting for PIDS: 28800

The process hangs

**Comment by moisseev** [comment] 2015-11-25 11:28
Hi @dehnli,
what hardware platform are you using?

I have b25f5df installed on two FreeBSD servers. On amd64 rmilter works without a problem. On i386 after updating to b25f5df I thought I had the issue, but then I got it worked somehow. Rmilter worked several days until rspamd and postfix was restarted.

Now on i386 1.6.6 hangs and TCP workaround helps, b25f5df hangs and TCP workaround doesn't help.

**Comment by vstakhov** [comment] 2015-11-25 11:56
Maybe you have old rmilter.sh script somewhere? Actually, I want to release 1.6.7 but I need to ensure first that all existing issues are fixed.

**Comment by moisseev** [comment] 2015-11-25 12:10
No, there is no old rmilter.sh anywhere on the affected system.

**Comment by dehnli** [comment] 2015-11-25 12:21
I'm stupid ( 
`uname -rip`
`10.1-RELEASE-p24 i386 GENERIC`
Not 
`$ sudo service postfix reload`
but
`$ sudo service postfix restart`
and restarting rmilter and rspamd helps in my case. And now 
`/usr/local/etc/rc.d/rmilter restart`
`Stopping rmilter.`
`Waiting for PIDS: 48313.`
`Starting rmilter.`
It means kAworu's patch helped.

**Comment by kAworu** [comment] 2015-11-25 12:28
@moisseev can you tell us what happen when you start rmilter "by hand" **using the `-n` option** ?

**Comment by moisseev** [comment] 2015-11-25 12:55
Unfortunately, I can't do it right now. I'll check this in 2-3 hours.

**Comment by moisseev** [comment] 2015-11-25 16:42
Testing d4be9f5 on i386 using TCP socket:
`# /usr/local/sbin/rmilter -n -c /usr/local/etc/rmilter.conf` works as expected
`# /usr/local/sbin/rmilter -c /usr/local/etc/rmilter.conf` works or hangs unpredictable

Configured with unix socket rmilter doesn't do any filtering at all and without `-n` option ignores `TERM` signal.

**Comment by vstakhov** [comment] 2015-11-25 16:45
Does `ktrace` or `truss` show anything usefull?

**Comment by moisseev** [comment] 2015-11-26 08:31
I don't know convenient way to post small binary files. So, I've sent `ktrace.out` in private.

**Comment by kAworu** [comment] 2015-11-26 10:12
@moisseev you should ktrace the process and then post the result of `kdump(1)` which is human readable. As I don't have a freebsd 9.3 i386 at hand I am unable to read it.

**Comment by moisseev** [comment] 2015-11-26 10:21
Sure. https://paste.rspamd.com/BMJ5

I've never mentioned 9.3
~~~
# uname -mrsv
FreeBSD 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 19:31:38 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  i386
~~~

**Comment by kAworu** [comment] 2015-11-26 12:08
@moisseev can you try this patch (against master) ? https://gist.github.com/kAworu/646ed7b1bb6240183d52 I'm testing it under amd64 and it seems ok. 

Since the problem is so hard to reproduce, I can't help wondering if spawning the reload_thread later would help, hence the patch.

**Comment by moisseev** [comment] 2015-11-26 12:38
@kAworu I've tested your patch under FreeBSD 10.2-RELEASE i386 with both TCP and unix sockets. It seems the patch fixed the issue.

**Comment by kAworu** [comment] 2015-11-26 14:34
@moisseev Ok thank you !

**Closed** 2015-12-03 06:14 UTC
